### ISSUE TITLE
Write better readme, add Licence

### ISSUE THREAD

**Issue by kmjayadeep** [kmjayadeep/menjar-chef#2]

**Comment by kodekage** [comment]
What Open source Licence do you want to add? Also What's I'd appreciate you explaining what the project is about to be able to write a better ReadMe

**Comment by amrithm98** [comment]
> What Open source Licence do you want to add? Also What's I'd appreciate you explaining what the project is about to be able to write a better ReadMe

The README is updated. Thank you for the support.
